/* Generated By:JavaCC: Do not edit this line. PointerGrammarConstants.java */
package org.xbrlapi.xpointer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PointerGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NormalChar = 2;
  /** RegularExpression Id. */
  int LeftDataBracket = 3;
  /** RegularExpression Id. */
  int RightBracket = 4;
  /** RegularExpression Id. */
  int EscapedChar = 5;
  /** RegularExpression Id. */
  int NCName = 6;
  /** RegularExpression Id. */
  int LeftBracket = 7;
  /** RegularExpression Id. */
  int NCNameChar = 8;
  /** RegularExpression Id. */
  int Letter = 9;
  /** RegularExpression Id. */
  int BaseChar = 10;
  /** RegularExpression Id. */
  int Ideographic = 11;
  /** RegularExpression Id. */
  int CombiningChar = 12;
  /** RegularExpression Id. */
  int Digit = 13;
  /** RegularExpression Id. */
  int Extender = 14;
  /** RegularExpression Id. */
  int Space = 15;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinSchemeData = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\":\"",
    "<NormalChar>",
    "\"(\"",
    "\")\"",
    "<EscapedChar>",
    "<NCName>",
    "\"(\"",
    "<NCNameChar>",
    "<Letter>",
    "<BaseChar>",
    "<Ideographic>",
    "<CombiningChar>",
    "<Digit>",
    "<Extender>",
    "<Space>",
  };

}
